-- Query 1
select cust_id from customer where cust_id not in( select distinct c.cust_id from CUSTOMER C, WALLET W
where C.WALLET_ID=W.WALLET_ID and W.B_ID  IN ('Brand02'));

--Query 2
SELECT W.CUST_ID, W.LP_ID FROM wallet W
WHERE NOT EXISTS(
	SELECT * FROM  CUSTOMER_ACTIVITIES CA
	WHERE W.WALLET_ID=CA.WALLET_ID AND W.LP_ID=CA.LP_ID);

--Query 3
SELECT * FROM REWARD R WHERE B_ID = 'Brand01';

--Query 4
SELECT RE_RULE.LP_ID 
FROM RE_RULE, ACTIVITY_TYPE 
WHERE ACTIVITY_TYPE.A_NAME = 'Refer a friend' AND ACTIVITY_TYPE.A_CODE = RE_RULE.A_CODE;

--Query 5 
SELECT RE.A_CODE, COUNT(*) AS CT
FROM RE_RULE RE, CUSTOMER_ACTIVITIES CA
WHERE RE.B_ID='Brand01' AND CA.B_ID=RE.B_ID AND CA.RE_RULE_CODE=RE.RE_RULE_CODE AND CA.RE_VERSION=RE.RE_VERSION
GROUP BY RE.A_CODE; 

--Query 6
SELECT WALLET_ID, COUNT(*) AS CT
FROM CUSTOMER_ACTIVITIES WHERE RR_RULE_CODE <> 'null' AND B_ID='Brand01'
GROUP BY WALLET_ID HAVING COUNT(*) >=2 ;

--Query 7
SELECT B_ID,SUM(R_POINTS) AS PTS FROM  WALLET GROUP BY B_ID HAVING SUM(R_POINTS) < 500;

--Query 8
SELECT COUNT(*) AS CT FROM CUSTOMER_ACTIVITIES 
WHERE B_ID = 'Brand02' AND RE_RULE_CODE<>'NULL' AND ACTIVITY_DATE>=DATE'2021-08-01' AND ACTIVITY_DATE<=DATE'2021-09-30' 
    AND WALLET_ID IN (SELECT WALLET_ID FROM WALLET WHERE CUST_ID = 'C0003');





